// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema(
    {
      carrier_id: String,
      carrier_name: String,
      carrier_code: String,
      service_code: String,
      shipstation_carrier_code: String,
      shipengine_carrier_code: String,
      alias: String,
      name: String,
      domestic: Boolean,
      international: Boolean,
      is_multi_package_supported: Boolean,
    },
    {
      timestamps: false,
    }
  );

  return mongoose.model("carrierServices", schema, "carrierServices");
};
